repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: pants-ruff
        name: Check Terraform files
        entry: ./internal/pre_commit_hooks/pants_ruff_fix.sh
        language: script
